### ISSUE TITLE
Add remaining methods in contract interact

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenST/brandedtoken.js#104]
There are some methods in contract interact which were not implemented. This ticket is to implement those methods. 

BT interact 
 * `liftAllRestrictions`
* `revokeStakeRequest`
* `redeem`
* `setSymbol`
* `setName`
* `transfer`
* `transferFrom`
* `convertToValueTokens`

GatewayComposer 
* `transferToken`
* `approveToken`
* `destroy`

**Comment by schemar** [comment]
Should this still be done in the light of auto-generated contract interacts?
