### ISSUE TITLE
Logging should be handled by a logger library

### ISSUE THREAD

**Issue by schemar** [OpenST/brandedtoken.js#107]
We should introduce a configurable logging library and replace `console.log` with it.

[winstonjs](https://github.com/winstonjs/winston) seems to be the favorite right now.

References #80 

/cc @benjaminbollen @sarvesh-ost

**Comment by sarvesh-ost** [comment]
Refer #86. Logger is configured in brandedtoken.js using winstonjs.

**Comment by schemar** [comment]
So this can be closed @sarvesh-ost ?

**Comment by sarvesh-ost** [comment]
> So this can be closed @sarvesh-ost ?

Yes, I think. 👍

**Comment by schemar** [comment]
👌
