### ISSUE TITLE
Functions in Facilitator must not accept any ABI's and originWeb3 as parameter

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/brandedtoken.js#89]
- EIP20Token ABI is standard and should not be passed as a parameter.
- originWeb3 is already available when the object is constructed. So originWeb3 is not needed in the parameter.

**Comment by schemar** [comment]
The `Facilitator` has only one method. Does this ticket apply to more than just the facilitator?

/cc @abhayks1 @deepesh-kn @sarvesh-ost

**Comment by abhayks1** [comment]
@schemar **Staker** also needs to be updated:
https://github.com/OpenSTFoundation/brandedtoken.js/blob/develop/lib/helpers/stake/gateway_composer/Staker.js#L66

**Comment by abhayks1** [comment]
Wait there is a separate ticket for Staker class update:
https://github.com/OpenSTFoundation/brandedtoken.js/issues/91
But it says "Staker function **must accept ABIs** in the parameter" 😕 cc: @deepesh-kn
